version: '3'

services:
  client:
    image: nlp-tripadvisor-client
    build:
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "8502:8502"
    environment:
      DOCKER_ENV: true
      SQLITE_PATH: /app/sql/tripadvisor.db
      MISTRAL_URL: http://mistralservice:8501
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    volumes:
      - ./sql:/app/sql
